api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/BankAccount/Application/Command'
            - '%kernel.project_dir%/src/BankAccount/Infrastructure/Doctrine'

    exception_to_status:
        \TypeError: 400
        \Symfony\Component\Serializer\Exception\UnexpectedValueException: 400
        \Symfony\Component\Serializer\Exception\MissingConstructorArgumentsException: 400

    formats:
        jsonld:   ['application/ld+json']
        jsonhal:  ['application/hal+json']
        jsonapi:  ['application/vnd.api+json']
        json:     ['application/json']
        xml:      ['application/xml', 'text/xml']
        yaml:     ['application/x-yaml']
        csv:      ['text/csv']
        html:     ['text/html']
