#framework:
#    messenger:
#        transports:
#            # Uncomment the following line to enable a transport named "amqp"
#            # amqp: '%env(MESSENGER_TRANSPORT_DSN)%'
#
#        routing:
#            # Route your messages to the transports
#            # 'App\Message\YourMessage': amqp
#
#        default_bus: messenger.bus.commands
#        buses:
#            messenger.bus.commands:
#                middleware:
#                    - Botilka\Infrastructure\Symfony\Messenger\Middleware\EventDispatcherBusMiddleware
#            messenger.bus.events: ~
#            messenger.bus.queries: ~
