version: '3.4'
services:
    php:
        build: .
        env_file:
            - .env
        depends_on:
            - postgres
            - elasticsearch
        volumes:
            - ./:/var/www/html

    nginx:
        image: nginx:1-alpine
        env_file:
            - .env
        depends_on:
            - php
        volumes:
            - ./public:/var/www/html/public:ro
            - ./var/nginx:/var/log/nginx
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

    postgres:
        image: postgres:10-alpine
        env_file:
            - .env
        volumes:
            - ./var/postgres:/var/lib/postgresql/data

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.0
        environment:
            - 'cluster.name=botilka'
            - 'discovery.type=single-node'
        volumes:
            - ./var/elasticsearch:/usr/share/elasticsearch/data

    mongodb:
        image: mongo:4
        volumes:
            - ./var/mongodb:/data/db
