version: '3.4'
services:
    php:
        build:
            context: .
            target: app-php_dev
        env_file:
            - .env
        depends_on:
            - postgres
            - elasticsearch
        volumes:
            - ./:/var/www/html
            - ~/.composer/cache:/root/.composer/cache

    nginx:
        image: nginx:1-alpine
        env_file:
            - .env
        depends_on:
            - php
        volumes:
            - ./public:/var/www/html/public:ro
            - ./var/nginx:/var/log/nginx
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

    postgres:
        image: postgres:12-alpine
        env_file:
            - .env
        volumes:
            - postgres-volume:/var/lib/postgresql/data

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.6
        environment:
            - 'cluster.name=botilka'
            - 'discovery.type=single-node'
        volumes:
            - elasticsearch-volume:/usr/share/elasticsearch/data

    mongodb:
        image: mongo:4
        volumes:
            - mongodb-volume:/data/db

volumes:
    postgres-volume:
    elasticsearch-volume:
    mongodb-volume:
